feat: initial docker setup
JanTry/IO_TEAM_B_20-21 pull request #51
Opened 2021-03-24 11:23 UTC by hoob3rt

WIP docker setup

`docker-compose up` builds backend and creates 3 containers:
* express.js api
* mongo db
* react fe with live reloading on code change

### TODO
- [x] connect api & fe containers
- [ ] use env variables for all ports
- [ ] test db connection (@JanTry nie wiem jak ma ta baza dzialac, nie laczy mi sie to)

### Issues
backendowcy napiszcie mi czy chcecie live realoading tam

2021-03-29 13:42 UTC, JanTry commented
Połączenie nie było wywoływane z index.ts, ale z dbSetup.ts, tak jak pisałem w readme

2021-03-29 13:45 UTC, JanTry requested changes
Update readme

2021-03-30 23:26 UTC, hoob3rt commented
imo jest gotowe. Rozdzielilem to jednak poniewaz sa to 2 rozne serwisy. `README.md` odpowiednio zaktualizowane

2021-03-31 09:17 UTC, JanTry approved these changes

2021-03-31 09:18 UTC, merged