WiP: New user's fields: firstName, lastName
JanTry/IO_TEAM_B_20-21 pull request #79
Opened 2021-04-19 22:01 UTC by WojtAcht

2021-04-20 07:12 UTC, szarbartosz approved these changes

2021-04-20 08:25 UTC, szarbartosz requested changes

2021-04-20 08:25 UTC, szarbartosz commented on backend/src/database/collectionsUtils/userUtils.ts
>        name: `NAME_${i}`,
czy tego jeszcze potrzebujemy?

2021-04-20 08:25 UTC, szarbartosz commented on backend/src/database/models/user.ts
>    name?: string;
up

2021-04-20 09:08 UTC, JanTry commented
Potrzebujemy tej zmiany w ogóle?
Nie możemy traktować name jako imienia, surname jako nazwiska i tyle? Po co ta zmiana?

2021-04-20 11:35 UTC, WojtAcht commented
> Potrzebujemy tej zmiany w ogóle?
> Nie możemy traktować name jako imienia, surname jako nazwiska i tyle? Po co ta zmiana?

Moglibyśmy korzystać z jednego pola name, ale uznałem, że jeśli i tak zmieniam w /auth/register to zmienię na firstName i lastName żeby było bardziej estetycznie.

2021-04-20 12:54 UTC, JanTry commented
Ale nie chodzi o jedno pole. Tylko 2. Tam wczesniej juz bylo osobno name i surname. Prosta zmiana name na firstname zalatwi sprawę

2021-04-20 14:49 UTC, WojtAcht commented
oki - wcześniej nie zauważyłem, że było i name i surname xd więc ostatecznie zmieniłem po prostu name, surname -> firstName, lastName

2021-04-21 06:32 UTC, szarbartosz approved these changes

2021-04-21 07:26 UTC, JanTry approved these changes

2021-04-21 10:54 UTC, kpodsiad approved these changes
lgtm

2021-04-21 10:54 UTC, merged